services:
  commentservice.api:
    image: commentservice.api
    build:
      context: .
      dockerfile: CommentService.API/Dockerfile
    environment:
      - ConnectionStrings__Postgres=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};KeepAlive=30;Pooling=true;
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT}
      - ConnectionStrings__YARP=${YARP_HOST}:${YARP_PORT}
      - Redis__InstanceName=${REDIS_INSTANCE_NAME}
      - Comment__VideoStartPath=${COMMENT_VIDEO_START_PATH}
      - Comment__PictureStartPath=${COMMENT_PICTURE_START_PATH}
      - Logs__Path=${LOGS_PATH}
      - Kafka__PersonCreated__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__PersonCreated__Topic=${KAFKA_TOPIC_PERSON_CREATED}
      - Kafka__PersonCreated__GroupId=${KAFKA_GROUP_PERSON_CREATED}
      - Kafka__PersonDeleted__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__PersonDeleted__Topic=${KAFKA_TOPIC_PERSON_DELETED}
      - Kafka__PersonDeleted__GroupId=${KAFKA_GROUP_PERSON_DELETED}
      - Kafka__MusicDeleted__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__MusicDeleted__Topic=${KAFKA_TOPIC_MUSIC_DELETED}
      - Kafka__MusicDeleted__GroupId=${KAFKA_GROUP_MUSIC_DELETED}
      - FFmpeg__Path=${FFMPEG_PATH}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__PublicKey=${JWT_PUBLIC_KEY}
    networks:
      - music-solution-network
    volumes:
      - video_data:${COMMENT_VIDEO_START_PATH}
      - picture_data:${COMMENT_PICTURE_START_PATH}
      - logs_data:${LOGS_PATH}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.11
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Databases/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music-solution-network

networks:
  music-solution-network:
    external: true

volumes:
  postgres_data:
  video_data:
  picture_data:
  logs_data: