<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CommentService.Domain\CommentService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="6.0.0-preview.4.21253.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
      <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    </ItemGroup>

</Project>
