services:
  musicservice.api:
    image: musicservice.api
    build:
      context: .
      dockerfile: MusicService.API/Dockerfile
    environment:
      - ConnectionStrings__Postgres=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT}
      - ConnectionStrings__YARP=${YARP_HOST}:${YARP_PORT}
      - Redis__InstanceName=${REDIS_INSTANCE_NAME}
      - Music__StartPath=${MUSIC_START_PATH}
      - Logs__Path=${LOGS_PATH}
      - Socket__Port=${SOCKET_PORT}
      - Kafka__MusicCreated__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__MusicCreated__Topic=${KAFKA_TOPIC_CREATED}
      - Kafka__MusicDeleted__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__MusicDeleted__Topic=${KAFKA_TOPIC_DELETED}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__PublicKey=${JWT_PUBLIC_KEY}
    networks:
      - music-solution-network
    volumes:
      - music_data:${MUSIC_START_PATH}
      - logs_data:${LOGS_PATH}
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:16.11
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Databases/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music-solution-network

networks:
  music-solution-network:
    external: true

volumes:
  postgres_data:
  music_data:
  logs_data: