services:
  userservice.api:
    image: userservice.api
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    environment:
      - ConnectionStrings__Postgres=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT},abortConnect=false
      - ConnectionStrings__YARP=${YARP_HOST}:${YARP_PORT}
      - Logs__Path=${LOGS_PATH}
      - Kafka__PersonCreated__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__PersonCreated__Topic=${KAFKA_TOPIC_PERSON_CREATED}
      - Kafka__PersonDeleted__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__PersonDeleted__Topic=${KAFKA_TOPIC_PERSON_DELETED}
      - Kafka__PersonUpdated__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
      - Kafka__PersonUpdated__Topic=${KAFKA_TOPIC_PERSON_UPDATED}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__PrivateKey=${JWT_PRIVATE_KEY}
      - Jwt__PublicKey=${JWT_PUBLIC_KEY}
    networks:
      - music-solution-network
    volumes:
      - logs_data:${LOGS_PATH}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.11
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Databases/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music-solution-network

volumes:
  postgres_data:
  logs_data:

networks:
  music-solution-network:
    external: true